apiVersion: v1
kind: Service
metadata:
  labels:
    run: cddb-mysql
    visualize: "true"
  name: cddb-mysql
spec:
  ports:
  - port: 3306
    protocol: TCP
  selector:
    run: cddb-mysql
  sessionAffinity: None
  type: ClusterIP
