apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: nginx
    visualize: "true"
  name: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      visualize: "true"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: nginx
        visualize: "true"
    spec:
      containers:
      - image: awassink/nginx-withcontent:3
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
