apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx
    visualize: "true"
  name: nginx
spec:
  ports:
  - port: 90
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  sessionAffinity: None
  type: LoadBalancer
